# Generated by Django 5.0.6 on 2024-07-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название вакансии')),
                ('adress', models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес')),
                ('employer', models.CharField(max_length=150, verbose_name='Работодатель')),
                ('published', models.DateTimeField(verbose_name='Дата публикации')),
                ('salary', models.CharField(blank=True, max_length=20, null=True, verbose_name='Зарплата')),
                ('employment', models.CharField(max_length=50, verbose_name='Занятость')),
                ('experience', models.CharField(max_length=50, verbose_name='Опыт работы')),
                ('area', models.CharField(max_length=80, verbose_name='Регион')),
                ('profRole', models.CharField(max_length=100, verbose_name='Специальность')),
            ],
        ),
    ]
