# Generated by Django 5.0.6 on 2024-07-05 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='adress',
            new_name='address',
        ),
    ]
