# Generated by Django 5.0.6 on 2024-07-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_vacancy_options_remove_vacancy_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.CharField(blank=True, max_length=65, null=True, verbose_name='Зарплата'),
        ),
    ]
