# Generated by Django 5.0.6 on 2024-07-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_vacancy_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название вакансии'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='profRole',
            field=models.CharField(max_length=150, verbose_name='Специальность'),
        ),
    ]
