# Generated by Django 5.0.6 on 2024-07-05 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_vacancy_area_alter_vacancy_employment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='employment',
            field=models.CharField(max_length=80, verbose_name='Занятость'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='experience',
            field=models.CharField(max_length=80, verbose_name='Опыт работы'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Зарплата'),
        ),
    ]
