# Generated by Django 5.0.6 on 2024-07-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_vacancy_employment_alter_vacancy_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='profRole',
            field=models.CharField(max_length=200, verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Зарплата'),
        ),
    ]
