# Generated by Django 5.0.6 on 2024-07-05 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_vacancy_profrole_alter_vacancy_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='employer',
            field=models.CharField(max_length=200, verbose_name='Работодатель'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название вакансии'),
        ),
    ]
